# Generated by Django 5.0.7 on 2024-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_leader',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
