# Generated by Django 5.0.7 on 2024-08-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_team_leader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
