export const GET_LEADS = 'GET_LEADS';
export const DELETE_LEAD = 'DELETE_LEAD';
export const ADD_LEAD = 'ADD_LEAD';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_LEADS = 'CLEAR_LEADS';

//Teams
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER';
export const CHANGE_TEAM_LEADER = 'CHANGE_TEAM_LEADER';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAIL = 'CREATE_TEAM_FAIL';
export const REMOVE_TEAM_MEMBER_SUCCESS = 'REMOVE_TEAM_MEMBER_SUCCESS';
export const REMOVE_TEAM_MEMBER_FAIL = 'REMOVE_TEAM_MEMBER_FAIL';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL';

//Tasks
export const ADD_TASK = 'ADD_TASK';
export const GET_TASKS = 'GET_TASKS';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const REQUEST_EXTENSION = 'REQUEST_EXTENSION';
export const APPROVE_EXTENSION = 'APPROVE_EXTENSION';
export const REJECT_EXTENSION = 'REJECT_EXTENSION';
export const GET_EXTENSION_REQUESTS = 'GET_EXTENSION_REQUESTS'
